name: kitap_sarayi_app
description: Geleceğe yatırım.

publish_to: 'Shiori' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.2

  #register tarih alma widget
  cupertino_date_textbox: ^1.0.3  
  
  #splash animasyon
  animated_text_kit: ^4.2.2

  # firebase paketleri
  firebase_core: ^2.13.0
  firebase_storage: ^11.1.0
  firebase_database: ^10.1.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1 

  #provider
  equatable: ^2.0.5
  flutter_riverpod: ^2.3.6

  dio: ^5.1.2
  hive: ^2.2.3

  # Listede ifadeyi arama ve seçme
  flutter_typeahead: ^4.6.0

  # dosya alma ve işleme
  file_picker: ^5.0.0
  share_plus: ^6.3.0
  path_provider_windows: ^2.1.6  
  url_launcher: ^6.0.0
  excel: ^2.1.0
  win32: ^3.0.0
  path: ^1.8.3
  #state yönetimi kolaylaştırma
  kartal: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
      - assets/Logo/
      - assets/Icons/

fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 700
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis-Bold.ttf
        - asset: fonts/Dosis-SemiBold.ttf
        - asset: assets/fonts/Dosis-Regular.ttf
          weight: 700